version: '3.8'

services:
  clashdrive:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clashdrive
    restart: unless-stopped
    ports:
      - "5173:5173"
    command: ["bun", "x", "serve", "-s", "dist", "-l", "5173"]
